# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNvS8tj78_U9V_V28_L5ESMKhJ9GC79L
"""

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import time

class SoccerEnvironment:
    """The 'E' in PEAS: The Pitch and Ball"""
    def __init__(self):
        self.width = 100
        self.height = 60
        self.ball_pos = np.array([50.0, 30.0])
        self.goal_pos = np.array([100.0, 30.0])

    def reset(self):
        self.ball_pos = np.array([np.random.uniform(20, 80), np.random.uniform(10, 50)])
        return self.ball_pos

class PEASAgent:
    def __init__(self, start_pos=[10, 10]):
        self.pos = np.array(start_pos, dtype=float)
        self.speed = 3.0
        self.performance = 0 # 'P' in PEAS: Score tracking

    def sense(self, env):
        """'S' in PEAS: Sensors (Get ball and goal positions)"""
        return env.ball_pos, env.goal_pos

    def act(self, ball_pos, goal_pos):
        """'A' in PEAS: Actuators (Movement and Kicking)"""
        # Calculate vector to ball
        to_ball = ball_pos - self.pos
        distance = np.linalg.norm(to_ball)

        if distance > 2.0:
            # Move toward ball
            direction = to_ball / distance
            self.pos += direction * self.speed
            return "MOVING"
        else:
            # Kick ball toward goal
            kick_dir = goal_pos - ball_pos
            kick_dist = np.linalg.norm(kick_dir)
            ball_move = (kick_dir / kick_dist) * 10.0
            return ball_move

# --- Simulation Loop ---
env = SoccerEnvironment()
agent = PEASAgent()
ball_pos = env.reset()

fig, ax = plt.subplots(figsize=(10, 6))

for frame in range(25):
    # 1. Sense
    percept_ball, percept_goal = agent.sense(env)

    # 2. Act
    action = agent.act(percept_ball, percept_goal)

    if isinstance(action, np.ndarray):
        env.ball_pos += action # Ball was kicked
        agent.performance += 1 # Improved performance score

    # 3. Visualize
    ax.clear()
    # Draw Pitch
    ax.set_facecolor('#44a044')
    ax.add_patch(plt.Rectangle((0, 0), 100, 60, fill=False, color='white', linewidth=2))
    ax.axvline(50, color='white') # Halfway line

    # Draw Goal
    ax.add_patch(plt.Rectangle((98, 20), 2, 20, color='white', alpha=0.3))

    # Draw Agent and Ball
    ax.scatter(agent.pos[0], agent.pos[1], color='blue', s=200, label='Agent (Actuator)')
    ax.scatter(env.ball_pos[0], env.ball_pos[1], color='white', s=100, edgecolors='black', label='Ball')

    ax.set_title(f"PEAS Soccer Agent - Performance: {agent.performance}")
    ax.set_xlim(-5, 105)
    ax.set_ylim(-5, 65)
    ax.legend(loc='upper left')

    display(fig)
    clear_output(wait=True)
    time.sleep(0.1)